// svelte/src/Comments.svelte
<script lang="ts">
    import { onMount } from 'svelte';
    import type { CommentsProps } from '../../types';
    import { addComments } from '../../helper';
    
    type $$Props = CommentsProps;
    let ref;

    onMount(() => addComments($$props as CommentsProps, ref!));
</script>

<div bind:this={ref}></div>

// react/src/comments.tsx
import React, { useEffect, useRef } from 'react';
import type { CommentsProps } from '../../types';
import { addComments } from '../../helper';

export function Comments(props: CommentsProps) {

    const ref = useRef<null | HTMLDivElement>(null);

    useEffect(() => addComments(props, ref.current!), []);

    return <div ref={ref}></div>

}
